#!/bin/bash
#this program allows you to download music from youtube videos in mp3 format
input="cc"

until [[ -z "${input// }" ]]; do
	input=$(zenity --forms --title="yotubeDownloader" --text="Empty string to stop" --add-entry="Link" )
	if [[ -z "${input// }" ]]; then 
		echo "Closing youtubeDownloader"
	else
		youtube-dl --extract-audio --audio-format mp3 $input	
	fi
done

